<a href="https://colab.research.google.com/github/Jeswin-t/MSc-Dissertation-Web-Bot-Analysis/blob/main/M4D_Mouse_Move_CSV.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#**Mouse Movement Data Preparation Pipeline**

Step 1: Import required libraries

Step 2: Connect Google Drive

Step 3: Set M4D dataset location

Step 4: Check Phase 1 and Phase 2 folders

Step 5: Find mouse JSON files

Step 6: Inspect one raw mouse record

Step 7: Read Phase 1 session labels

Step 8: Calculate mouse features

Step 9: Process Phase 1 mouse sessions

Step 10: Process Phase 2 mouse sessions

Step 11: Combine Phase 1 and Phase 2

Step 12: Check the M4D mouse dataset

Step 13: Check duplicate sessions

Step 14: Verify duplicate sessions

Step 15: Check exact duplicate rows

Step 16: Remove confirmed duplicate sessions

Step 17: Final dataset validation

Step 18: Save the final M4D mouse CSV

#STEP 1 : Import Required Libraries

In [ ]:
# ============================================================
# STEP 1 : Import Libraries
# ============================================================

# Import Google Drive
# It allows Colab to connect to and access files stored in Google Drive
from google.colab import drive


# Import OS
# It allows Python to work with folders, files, and file paths
import os


# Import glob so Python can search through folders
import glob


# Import the JSON library.
# It allows Python to read and work with JSON-formatted M4D files
import json



# Import mathematical functions
# Import Math for distance calculations
import math

# Import re for extracting mouse coordinates
import re

# Import NumPy for numerical operations
import numpy as np

# Import Pandas for creating and managing the CSV dataset
import pandas as pd

#STEP 2 - Connect Google Drive

In [ ]:
# ============================================================
# STEP 2 : CONNECT GOOGLE DRIVE
# ============================================================

# Mount Google Drive to Colab
drive.mount("/content/drive")

Mounted at /content/drive

#STEP 3 - Set M4D dataset location

In [ ]:
# ============================================================
# STEP 3 : SET THE M4D DATASET LOCATION
# ============================================================

# Folder containing the M4D dataset
m4d_dataset_folder = "/content/drive/MyDrive/DISSERTATION/DATASET/RAW DATASET/web_bot_detection_raw_dataset-M4D"

# Check whether the folder exists
if os.path.exists(m4d_dataset_folder):
    print("M4D dataset folder found.")
else:
    print("M4D dataset folder NOT found.")
    print("Check the folder name and location.")

M4D dataset folder found.

#STEP 4 - Check Phase 1 and Phase 2 folders

In [ ]:
# ============================================================
# STEP 4 : CHECK M4D PHASE FOLDERS
# ============================================================

# Create the Phase 1 folder path
phase1_folder = os.path.join(
    m4d_dataset_folder,
    "phase1"
)

# Create the Phase 2 folder path
phase2_folder = os.path.join(
    m4d_dataset_folder,
    "phase2"
)

# Check Phase 1
if os.path.exists(phase1_folder):
    print("Phase 1 found.")
else:
    print("Phase 1 NOT found.")

# Check Phase 2
if os.path.exists(phase2_folder):
    print("Phase 2 found.")
else:
    print("Phase 2 NOT found.")

Phase 1 found.
Phase 2 found.

#STEP 5 - Find mouse JSON files

In [ ]:
# ============================================================
# STEP 5 : FIND MOUSE-MOVEMENT JSON FILES
# ============================================================

# Search for all JSON files inside mouse_movements folders
mouse_json_files = glob.glob(
    os.path.join(
        m4d_dataset_folder,
        "**",
        "mouse_movements",
        "**",
        "*.json"
    ),
    recursive=True
)

# Display the number of files found
print("Total mouse JSON files found:", len(mouse_json_files))

# Display the first 20 files
print("\nFirst 20 mouse files:")

for mouse_file in mouse_json_files[:20]:

    print(mouse_file)

Total mouse JSON files found: 203

First 20 mouse files:
/content/drive/MyDrive/DISSERTATION/DATASET/RAW DATASET/web_bot_detection_raw_dataset-M4D/phase2/data/mouse_movements/humans/mouse_movements_humans.json
/content/drive/MyDrive/DISSERTATION/DATASET/RAW DATASET/web_bot_detection_raw_dataset-M4D/phase2/data/mouse_movements/bots/mouse_movements_advanced_bots.json
/content/drive/MyDrive/DISSERTATION/DATASET/RAW DATASET/web_bot_detection_raw_dataset-M4D/phase2/data/mouse_movements/bots/mouse_movements_moderate_bots.json
/content/drive/MyDrive/DISSERTATION/DATASET/RAW DATASET/web_bot_detection_raw_dataset-M4D/phase1/data/mouse_movements/humans_and_advanced_bots/0i5kvpslrq3vb6u8ff2kuejv0v/mouse_movements.json
/content/drive/MyDrive/DISSERTATION/DATASET/RAW DATASET/web_bot_detection_raw_dataset-M4D/phase1/data/mouse_movements/humans_and_advanced_bots/1afcff96kgdbmevi5aemi5mkuj/mouse_movements.json
/content/drive/MyDrive/DISSERTATION/DATASET/RAW DATASET/web_bot_detection_raw_dataset-M4D/phase1/data/mouse_movements/humans_and_advanced_bots/1aqgqrcuurlmvvbbpirvsh7e53/mouse_movements.json
/content/drive/MyDrive/DISSERTATION/DATASET/RAW DATASET/web_bot_detection_raw_dataset-M4D/phase1/data/mouse_movements/humans_and_advanced_bots/16r8lv9fabgjk06di8usnmu9ni/mouse_movements.json
/content/drive/MyDrive/DISSERTATION/DATASET/RAW DATASET/web_bot_detection_raw_dataset-M4D/phase1/data/mouse_movements/humans_and_advanced_bots/071tbv7fsev5d64kb0f9jieor6/mouse_movements.json
/content/drive/MyDrive/DISSERTATION/DATASET/RAW DATASET/web_bot_detection_raw_dataset-M4D/phase1/data/mouse_movements/humans_and_advanced_bots/0oa2dua3mli7mrr32c0gd4o0i2/mouse_movements.json
/content/drive/MyDrive/DISSERTATION/DATASET/RAW DATASET/web_bot_detection_raw_dataset-M4D/phase1/data/mouse_movements/humans_and_advanced_bots/0p0kaqfmftrtfg0u12rkshrdi9/mouse_movements.json
/content/drive/MyDrive/DISSERTATION/DATASET/RAW DATASET/web_bot_detection_raw_dataset-M4D/phase1/data/mouse_movements/humans_and_advanced_bots/1r170g6lqfoff21od5nn9f976a/mouse_movements.json
/content/drive/MyDrive/DISSERTATION/DATASET/RAW DATASET/web_bot_detection_raw_dataset-M4D/phase1/data/mouse_movements/humans_and_advanced_bots/1ttvuqau08dh4t1cjg50pr2298/mouse_movements.json
/content/drive/MyDrive/DISSERTATION/DATASET/RAW DATASET/web_bot_detection_raw_dataset-M4D/phase1/data/mouse_movements/humans_and_advanced_bots/20054o9vd2q32sqnc3g6kj17om/mouse_movements.json
/content/drive/MyDrive/DISSERTATION/DATASET/RAW DATASET/web_bot_detection_raw_dataset-M4D/phase1/data/mouse_movements/humans_and_advanced_bots/26v7bi8e0oc7p58e3s9v8eic9f/mouse_movements.json
/content/drive/MyDrive/DISSERTATION/DATASET/RAW DATASET/web_bot_detection_raw_dataset-M4D/phase1/data/mouse_movements/humans_and_advanced_bots/3ctnavj7r6jrdpq5q0n8s7s4l1/mouse_movements.json
/content/drive/MyDrive/DISSERTATION/DATASET/RAW DATASET/web_bot_detection_raw_dataset-M4D/phase1/data/mouse_movements/humans_and_advanced_bots/3uqepgd76f9ecnauehcl4sucbh/mouse_movements.json
/content/drive/MyDrive/DISSERTATION/DATASET/RAW DATASET/web_bot_detection_raw_dataset-M4D/phase1/data/mouse_movements/humans_and_advanced_bots/4j64bd6drdkbib7sfpaue62poi/mouse_movements.json
/content/drive/MyDrive/DISSERTATION/DATASET/RAW DATASET/web_bot_detection_raw_dataset-M4D/phase1/data/mouse_movements/humans_and_advanced_bots/49rbuft0lmtfjd3qn70np3lk51/mouse_movements.json
/content/drive/MyDrive/DISSERTATION/DATASET/RAW DATASET/web_bot_detection_raw_dataset-M4D/phase1/data/mouse_movements/humans_and_advanced_bots/4mae49mh8va4g03vjatfn6np9b/mouse_movements.json
/content/drive/MyDrive/DISSERTATION/DATASET/RAW DATASET/web_bot_detection_raw_dataset-M4D/phase1/data/mouse_movements/humans_and_advanced_bots/7f2bg9n48opuf4ligvtc1dsopr/mouse_movements.json

#STEP 6 - Inspect one raw mouse file

In [ ]:
# ============================================================
# STEP 6 : INSPECT ONE RAW M4D MOUSE RECORD
# ============================================================

# Select the first mouse JSON file found earlier
example_mouse_file = mouse_json_files[0]

# Display the selected file path
print("Inspecting file:")
print(example_mouse_file)

print("\n" + "=" * 70)

# Open the selected mouse JSON file
with open(
    example_mouse_file,
    "r",
    encoding="utf-8"
) as mouse_file:

    # Read only the first record
    first_record_line = mouse_file.readline()

# Convert the JSON text into Python data
example_mouse_record = json.loads(first_record_line)


# ------------------------------------------------------------
# DISPLAY RECORD TYPE
# ------------------------------------------------------------

print("\nType of first record:")
print(type(example_mouse_record))


# ------------------------------------------------------------
# DISPLAY ALL AVAILABLE FIELDS
# ------------------------------------------------------------

print("\nFields available in the first mouse record:")

for field_name in example_mouse_record.keys():
    print("-", field_name)


# ------------------------------------------------------------
# CHECK MOUSE BEHAVIOUR
# ------------------------------------------------------------

print("\nExample mouse behaviour:")

print(
    repr(
        example_mouse_record.get(
            "mousemove_total_behaviour"
        )
    )
)


# ------------------------------------------------------------
# CHECK MOUSE TIMESTAMPS
# ------------------------------------------------------------

print("\nExample mouse timestamps:")

print(
    repr(
        example_mouse_record.get(
            "mousemove_times"
        )
    )
)


# ------------------------------------------------------------
# CHECK TIMESTAMP DATA TYPE
# ------------------------------------------------------------

print("\nTimestamp data type:")

print(
    type(
        example_mouse_record.get(
            "mousemove_times"
        )
    )
)

Inspecting file:
/content/drive/MyDrive/DISSERTATION/DATASET/RAW DATASET/web_bot_detection_raw_dataset-M4D/phase2/data/mouse_movements/humans/mouse_movements_humans.json

======================================================================

Type of first record:
<class 'dict'>

Fields available in the first mouse record:
- _id
- session_id
- mousemove_client_height_width
- mousemove_times
- mousemove_total_behaviour
- mousemove_visited_urls
- unique_id

Example mouse behaviour:

#STEP 7 - Read the Phase 1 labels

In [ ]:
# ============================================================
# STEP 7 : READ PHASE 1 SESSION LABELS
# ============================================================


# Create an empty dictionary to store the Phase 1 labels
# The dictionary will connect each session ID to its class label
phase1_session_labels = {}


# Create a list containing the locations of the four Phase 1 annotation files
phase1_annotation_files = [


    # Create the path to the training annotation file for Human vs Advanced Bot sessions
    os.path.join(
        phase1_folder,
        "annotations",
        "humans_and_advanced_bots",
        "train"
    ),


    # Create the path to the testing annotation file for Human vs Advanced Bot sessions
    os.path.join(
        phase1_folder,
        "annotations",
        "humans_and_advanced_bots",
        "test"
    ),


    # Create the path to the training annotation file for Human vs Moderate Bot sessions
    os.path.join(
        phase1_folder,
        "annotations",
        "humans_and_moderate_bots",
        "train"
    ),


    # Create the path to the testing annotation file for Human vs Moderate Bot sessions
    os.path.join(
        phase1_folder,
        "annotations",
        "humans_and_moderate_bots",
        "test"
    )

]


# Go through each annotation file in the list
for annotation_file in phase1_annotation_files:


    # Open the current annotation file
    # "r" means read mode
    # UTF-8 specifies how the text should be read
    with open(
        annotation_file,
        "r",
        encoding="utf-8"
    ) as annotation_data:


        # Read the annotation file one line at a time
        for line in annotation_data:


            # Remove unnecessary spaces and newline character from the beginning and end of the line
            # Then split the line into separate values.
            line_parts = line.strip().split()


            # Check that the line contains exactly two values
            if len(line_parts) == 2:


                # Take the first value as the session ID
                session_id = line_parts[0]


                # Take the second value as the session label
                session_label = line_parts[1]


                # Store the session ID and its label inside the dictionary
                phase1_session_labels[
                    session_id
                ] = session_label


# Print a heading and the total number of unique labelled Phase 1 sessions found
print(
    "Phase 1 labelled sessions:",
    len(phase1_session_labels)
)


# Print a heading before displaying example labels
print("\nExample Phase 1 labels:")


# Convert the dictionary items into a list
# [:10] selects only the first 10 examples so that the output does not become unnecessarily large
for session_id, session_label in list(
    phase1_session_labels.items()
)[:10]:


    # Display the session ID together with its label
    print(
        session_id,
        "→",
        session_label
    )

Phase 1 labelled sessions: 150

Example Phase 1 labels:
dr09rk5eagjuu87gedvdqmq3gl → human
gq715ms79515gcq39vf91mli6t → human
hrbko2t4t14q3pahqltndlolb5 → human
nvmlnfhs5v6hehsd81e9mf75cn → human
brrlh9tmiodt2ekkjvn7kcsps0 → human
s74076j0vtua7ct0fkej7ehmt8 → human
9ucesp41db4848uq9h8of7fcgd → human
k5pg7u2907cb9nk61dd8i15fm2 → human
ajpjcn74cv2ta0boepifbre3pe → human
8h83euesdq85f0shmjm34alpln → human

#STEP 8 - Create a function to calculate mouse features

In [ ]:
# ============================================================
# STEP 8 : FUNCTION TO CALCULATE MOUSE FEATURES
# ============================================================


# Create a pattern to identify mouse movement coordinates
# stored in the format [m(x,y)]
mouse_coordinate_pattern = re.compile(
    r'\[m\(\s*(-?\d+)\s*,\s*(-?\d+)\s*\)\]'
)


# Create a function that receives mouse behaviour
# and mouse timestamp data
def calculate_mouse_features(
    mouse_behaviour,
    mouse_times
):


    # --------------------------------------------------------
    # 1. EXTRACT MOUSE COORDINATES
    # --------------------------------------------------------

    # Convert missing mouse behaviour into empty text
    if mouse_behaviour is None:
        mouse_behaviour = ""

    # Make sure mouse behaviour is text
    mouse_behaviour = str(
        mouse_behaviour
    )


    # Extract all [m(x,y)] coordinates
    mouse_coordinates = [

        (
            int(x),
            int(y)
        )

        for x, y in mouse_coordinate_pattern.findall(
            mouse_behaviour
        )
    ]


    # --------------------------------------------------------
    # 2. COUNT MOUSE MOVEMENT EVENTS
    # --------------------------------------------------------

    # Number of mouse movement coordinates
    mouse_events = len(
        mouse_coordinates
    )


    # --------------------------------------------------------
    # 3. CALCULATE TOTAL MOUSE DISTANCE
    # --------------------------------------------------------

    # Start total distance at zero
    total_distance = 0.0


    # Compare every mouse position with the next position
    for first_point, second_point in zip(
        mouse_coordinates,
        mouse_coordinates[1:]
    ):


        # Separate first coordinate
        first_x, first_y = first_point


        # Separate second coordinate
        second_x, second_y = second_point


        # Calculate Euclidean distance
        distance_between_points = math.sqrt(

            (second_x - first_x) ** 2

            +

            (second_y - first_y) ** 2
        )


        # Add the distance to the session total
        total_distance += distance_between_points


    # --------------------------------------------------------
    # 4. READ AND CLEAN MOUSE TIMESTAMPS
    # --------------------------------------------------------

    # Create empty list for valid timestamps
    mouse_timestamps = []


    # Convert missing timestamp data into empty text
    if mouse_times is None:
        mouse_times = ""


    # Make sure timestamps are text
    mouse_times = str(
        mouse_times
    )


    # Extract all numerical values from the timestamp string
    timestamp_values = re.findall(
        r'\d+',
        mouse_times
    )


    # Convert timestamp values into integers
    for time_value in timestamp_values:


        try:

            timestamp = int(
                time_value
            )


            # Keep positive timestamp values
            if timestamp > 0:

                mouse_timestamps.append(
                    timestamp
                )


        except ValueError:

            # Ignore values that cannot be converted
            pass


    # --------------------------------------------------------
    # 5. REMOVE TIMESTAMPS WITH AN ABNORMAL DIGIT LENGTH
    # --------------------------------------------------------

    # Run this only when timestamps were found
    if mouse_timestamps:


        # Find the number of digits in every timestamp
        timestamp_lengths = [

            len(
                str(timestamp)
            )

            for timestamp in mouse_timestamps
        ]


        # Find the timestamp length that occurs most often
        most_common_length = max(

            set(
                timestamp_lengths
            ),

            key=timestamp_lengths.count
        )


        # Keep timestamps using the main format
        mouse_timestamps = [

            timestamp

            for timestamp in mouse_timestamps

            if len(
                str(timestamp)
            ) == most_common_length
        ]


    # --------------------------------------------------------
    # 6. CALCULATE MOUSE ACTIVITY DURATION
    # --------------------------------------------------------

    # Start duration as missing
    duration_seconds = np.nan


    # At least two timestamps are required
    if len(mouse_timestamps) >= 2:


        # Find earliest timestamp
        earliest_time = min(
            mouse_timestamps
        )


        # Find latest timestamp
        latest_time = max(
            mouse_timestamps
        )


        # Calculate duration in milliseconds
        duration_milliseconds = (
            latest_time
            -
            earliest_time
        )


        # Convert milliseconds into seconds
        duration_seconds = (
            duration_milliseconds
            /
            1000
        )


        # Replace zero or negative durations
        # with a missing value
        if duration_seconds <= 0:

            duration_seconds = np.nan


    # --------------------------------------------------------
    # 7. CALCULATE AVERAGE MOUSE SPEED
    # --------------------------------------------------------

    # Start average speed as missing
    avg_speed = np.nan


    # Calculate speed only when duration is valid
    if (
        pd.notna(duration_seconds)
        and duration_seconds > 0
    ):


        # Average mouse speed =
        # total mouse distance / duration
        avg_speed = (
            total_distance
            /
            duration_seconds
        )


    # --------------------------------------------------------
    # 8. RETURN THE CALCULATED FEATURES
    # --------------------------------------------------------

    return (

        mouse_events,

        duration_seconds,

        total_distance,

        avg_speed
    )

#STEP 9 - Process Phase 1 mouse sessions

In [ ]:
# ============================================================
# STEP 9 : PROCESS PHASE 1 MOUSE SESSIONS
# ============================================================


# Create an empty list to store the processed Phase 1 sessions
phase1_session_rows = []


# Search for all Phase 1 mouse_movements.json files
phase1_mouse_files = glob.glob(

    os.path.join(

        # Start from the Phase 1 folder
        phase1_folder,

        # Enter the data folder
        "data",

        # Enter the mouse_movements folder
        "mouse_movements",

        # Match either mouse comparison group folder
        "*",

        # Match every individual session folder
        "*",

        # Select the mouse movement JSON file
        "mouse_movements.json"
    )
)


# Display how many Phase 1 mouse files were found
print(
    "Phase 1 mouse files found:",
    len(phase1_mouse_files)
)


# Create a mapping to make Phase 1 labels
# match the Phase 2 label format
phase1_label_mapping = {

    "human": "Human",

    "moderate_bot": "Moderate Bot",

    "advanced_bot": "Advanced Bot"
}


# Go through every Phase 1 mouse file one at a time
for mouse_file in phase1_mouse_files:


    # Open the current Phase 1 mouse JSON file
    with open(
        mouse_file,
        "r",
        encoding="utf-8"
    ) as file:


        # Read the complete JSON file
        mouse_session_data = json.load(
            file
        )


    # --------------------------------------------------------
    # 1. GET SESSION ID
    # --------------------------------------------------------

    session_id = mouse_session_data.get(
        "session_id"
    )


    # Skip the file if the session ID is missing
    if session_id is None:

        print(
            "Missing session ID in:",
            mouse_file
        )

        continue


    # --------------------------------------------------------
    # 2. FIND SESSION LABEL
    # --------------------------------------------------------

    session_label = phase1_session_labels.get(
        session_id
    )


    # Check whether a label was found
    if session_label is None:

        print(
            "No label found:",
            session_id
        )

        continue


    # Convert Phase 1 labels into the same
    # format used for Phase 2
    session_label = phase1_label_mapping.get(
        session_label,
        session_label
    )


    # --------------------------------------------------------
    # 3. GET RAW MOUSE BEHAVIOUR
    # --------------------------------------------------------

    # Phase 1 stores the complete mouse movement behaviour
    # in the total_behaviour field
    mouse_behaviour = mouse_session_data.get(
        "total_behaviour",
        ""
    )


    # --------------------------------------------------------
    # 4. GET MOUSE TIMESTAMPS
    # --------------------------------------------------------

    mouse_times = mouse_session_data.get(
        "mousemove_times",
        ""
    )


    # --------------------------------------------------------
    # 5. CALCULATE MOUSE FEATURES
    # --------------------------------------------------------

    (
        mouse_events,
        duration_seconds,
        total_distance,
        avg_speed

    ) = calculate_mouse_features(

        mouse_behaviour,
        mouse_times
    )


    # --------------------------------------------------------
    # 6. CREATE ONE SESSION ROW
    # --------------------------------------------------------

    session_row = {

        "session_id": session_id,

        "phase": "Phase 1",

        "label": session_label,

        "mouse_events": mouse_events,

        "duration_seconds": duration_seconds,

        "total_distance": total_distance,

        "avg_speed": avg_speed
    }


    # --------------------------------------------------------
    # 7. ADD SESSION TO PHASE 1 DATA
    # --------------------------------------------------------

    phase1_session_rows.append(
        session_row
    )


# ============================================================
# DISPLAY PHASE 1 RESULTS
# ============================================================


# Display the total number of Phase 1 sessions processed
print(
    "\nPhase 1 sessions processed:",
    len(phase1_session_rows)
)


# Display the Phase 1 class counts
print(
    "\nPhase 1 class counts:"
)


print(
    pd.Series(
        [
            row["label"]
            for row in phase1_session_rows
        ]
    ).value_counts()
)

Phase 1 mouse files found: 200

Phase 1 sessions processed: 200

Phase 1 class counts:
Human           100
Advanced Bot     50
Moderate Bot     50
Name: count, dtype: int64

#STEP 10 - Process Phase 2 mouse sessions

In [ ]:
# ============================================================
# STEP 10 : PROCESS PHASE 2 MOUSE SESSIONS
# ============================================================


# Create an empty list to store the processed Phase 2 sessions
phase2_session_rows = []


# Create a list containing the three Phase 2 mouse files
# Each file path is paired with its correct class label
phase2_mouse_files = [


    # Human mouse data
    (
        os.path.join(
            phase2_folder,
            "data",
            "mouse_movements",
            "humans",
            "mouse_movements_humans.json"
        ),

        "Human"
    ),


    # Moderate Bot mouse data
    (
        os.path.join(
            phase2_folder,
            "data",
            "mouse_movements",
            "bots",
            "mouse_movements_moderate_bots.json"
        ),

        "Moderate Bot"
    ),


    # Advanced Bot mouse data
    (
        os.path.join(
            phase2_folder,
            "data",
            "mouse_movements",
            "bots",
            "mouse_movements_advanced_bots.json"
        ),

        "Advanced Bot"
    )
]


# Go through each Phase 2 mouse file
# together with its assigned class label
for mouse_file, session_label in phase2_mouse_files:


    # Display which file is currently being processed
    print(
        "\nProcessing:",
        mouse_file
    )


    # Open the current Phase 2 JSON file
    with open(
        mouse_file,
        "r",
        encoding="utf-8"
    ) as file:


        # Phase 2 files contain multiple JSON records
        # Read them one line at a time
        for line in file:


            # Skip empty lines
            if not line.strip():

                continue


            # Convert the current JSON line
            # into a Python dictionary
            mouse_session_data = json.loads(
                line
            )


            # --------------------------------------------------------
            # 1. GET SESSION ID
            # --------------------------------------------------------

            session_id = mouse_session_data.get(
                "session_id"
            )


            # Skip the record if session ID is missing
            if session_id is None:

                print(
                    "Missing session ID in:",
                    mouse_file
                )

                continue


            # --------------------------------------------------------
            # 2. GET RAW MOUSE BEHAVIOUR
            # --------------------------------------------------------

            # Phase 2 stores the mouse movement behaviour
            # in mousemove_total_behaviour
            mouse_behaviour = mouse_session_data.get(
                "mousemove_total_behaviour",
                ""
            )


            # --------------------------------------------------------
            # 3. GET MOUSE TIMESTAMPS
            # --------------------------------------------------------

            mouse_times = mouse_session_data.get(
                "mousemove_times",
                ""
            )


            # --------------------------------------------------------
            # 4. CALCULATE MOUSE FEATURES
            # --------------------------------------------------------

            (
                mouse_events,
                duration_seconds,
                total_distance,
                avg_speed

            ) = calculate_mouse_features(

                mouse_behaviour,
                mouse_times
            )


            # --------------------------------------------------------
            # 5. CREATE ONE SESSION ROW
            # --------------------------------------------------------

            session_row = {

                # Unique session identifier
                "session_id": session_id,

                # Dataset phase
                "phase": "Phase 2",

                # Human, Moderate Bot or Advanced Bot
                "label": session_label,

                # Number of mouse movement events
                "mouse_events": mouse_events,

                # Mouse activity duration in seconds
                "duration_seconds": duration_seconds,

                # Total mouse movement distance
                "total_distance": total_distance,

                # Average mouse movement speed
                "avg_speed": avg_speed
            }


            # --------------------------------------------------------
            # 6. ADD SESSION TO PHASE 2 DATA
            # --------------------------------------------------------

            phase2_session_rows.append(
                session_row
            )


# ============================================================
# DISPLAY PHASE 2 RESULTS
# ============================================================


# Display the total number of Phase 2 sessions processed
print(
    "\nPhase 2 sessions processed:",
    len(phase2_session_rows)
)


# Display the Phase 2 class counts
print(
    "\nPhase 2 class counts:"
)

print(
    pd.Series(
        [
            row["label"]
            for row in phase2_session_rows
        ]
    ).value_counts()
)

Processing: /content/drive/MyDrive/DISSERTATION/DATASET/RAW DATASET/web_bot_detection_raw_dataset-M4D/phase2/data/mouse_movements/humans/mouse_movements_humans.json

Processing: /content/drive/MyDrive/DISSERTATION/DATASET/RAW DATASET/web_bot_detection_raw_dataset-M4D/phase2/data/mouse_movements/bots/mouse_movements_moderate_bots.json

Processing: /content/drive/MyDrive/DISSERTATION/DATASET/RAW DATASET/web_bot_detection_raw_dataset-M4D/phase2/data/mouse_movements/bots/mouse_movements_advanced_bots.json

Phase 2 sessions processed: 299

Phase 2 class counts:
Moderate Bot    120
Advanced Bot    120
Human            59
Name: count, dtype: int64

#STEP 11 - Combine Phase 1 and Phase 2

In [ ]:
# ============================================================
# STEP 11 : COMBINE PHASE 1 AND PHASE 2
# ============================================================


# Convert the processed Phase 1 session list into a Pandas DataFrame
phase1_dataframe = pd.DataFrame(
    phase1_session_rows
)


# Convert the processed Phase 2 session list into a Pandas DataFrame
phase2_dataframe = pd.DataFrame(
    phase2_session_rows
)


# Combine the Phase 1 and Phase 2 DataFrames into one M4D DataFrame
m4d_mouse_dataframe = pd.concat(

    # Provide the two DataFrames that need to be combined
    [
        phase1_dataframe,
        phase2_dataframe
    ],

    # Create a new continuous row index after combining the DataFrames
    ignore_index=True
)


# Display the number of rows and columns in the combined dataset
print(
    "M4D mouse dataset size:",
    m4d_mouse_dataframe.shape
)


# Display the first Ten rows of the combined M4D dataset
display(
    m4d_mouse_dataframe.head(10)
)

M4D mouse dataset size: (499, 7)

,session_id,phase,label,mouse_events,duration_seconds,total_distance,avg_speed
0,0i5kvpslrq3vb6u8ff2kuejv0v,Phase 1,Advanced Bot,8584,460.995,90825.917680,197.021481
1,1afcff96kgdbmevi5aemi5mkuj,Phase 1,Advanced Bot,7871,422.112,82255.555435,194.866660
2,1aqgqrcuurlmvvbbpirvsh7e53,Phase 1,Human,12182,310.202,125567.991635,404.794268
3,16r8lv9fabgjk06di8usnmu9ni,Phase 1,Advanced Bot,9402,427.428,94552.040289,221.211620
4,071tbv7fsev5d64kb0f9jieor6,Phase 1,Advanced Bot,12413,677.103,127571.108247,188.407241
5,0oa2dua3mli7mrr32c0gd4o0i2,Phase 1,Human,6933,160.409,85250.081718,531.454480
6,0p0kaqfmftrtfg0u12rkshrdi9,Phase 1,Human,6577,210.507,54442.552458,258.625853
7,1r170g6lqfoff21od5nn9f976a,Phase 1,Human,15834,445.151,163707.745609,367.757785
8,1ttvuqau08dh4t1cjg50pr2298,Phase 1,Advanced Bot,11972,586.952,120803.028099,205.814152
9,20054o9vd2q32sqnc3g6kj17om,Phase 1,Advanced Bot,8280,419.206,84259.960364,200.998937

#STEP 12 -  Checking the M4D mouse dataset

In [ ]:
# ============================================================
# STEP 12 : CHECK THE M4D MOUSE DATASET
# ============================================================


# ------------------------------------------------------------
# CHECK 1: COLUMN NAMES
# ------------------------------------------------------------

# Display a heading for the column names
print("COLUMN NAMES:")


# Convert all column names into a list and display them
print(
    m4d_mouse_dataframe.columns.tolist()
)


# ------------------------------------------------------------
# CHECK 2: DATASET SIZE
# ------------------------------------------------------------

# Display a heading for the dataset size
print("\nDATASET SIZE:")


# Display the total number of rows in the dataset
# shape[0] represents the number of rows
print(
    "Rows:",
    m4d_mouse_dataframe.shape[0]
)


# Display the total number of columns in the dataset
# shape[1] represents the number of columns
print(
    "Columns:",
    m4d_mouse_dataframe.shape[1]
)


# ------------------------------------------------------------
# CHECK 3: PHASE COUNTS
# ------------------------------------------------------------

# Display a heading for the Phase 1 and Phase 2 counts
print("\nPHASE COUNTS:")


# Count how many sessions belong to each phase
print(
    m4d_mouse_dataframe["phase"].value_counts()
)


# ------------------------------------------------------------
# CHECK 4: LABEL COUNTS
# ------------------------------------------------------------

# Display a heading for the class label counts
print("\nLABEL COUNTS:")


# Count how many sessions belong to each class label
print(
    m4d_mouse_dataframe["label"].value_counts()
)


# ------------------------------------------------------------
# CHECK 5: MISSING VALUES
# ------------------------------------------------------------

# Display a heading for the missing value check
print("\nMISSING VALUES:")


# Count the missing values in each column
print(
    m4d_mouse_dataframe.isnull().sum()
)


# ------------------------------------------------------------
# CHECK 6: DUPLICATE SESSION IDs
# ------------------------------------------------------------

# Count how many session IDs appear more than once
duplicate_session_count = (
    m4d_mouse_dataframe["session_id"]
    .duplicated()
    .sum()
)


# Display the number of duplicate session IDs found
print(
    "\nDUPLICATE SESSION IDs:",
    duplicate_session_count
)


# ------------------------------------------------------------
# CHECK 7: DATA TYPES
# ------------------------------------------------------------

# Display a heading for the column data types
print("\nDATA TYPES:")


# Display the data type of every column
print(
    m4d_mouse_dataframe.dtypes
)


# ------------------------------------------------------------
# CHECK 8: FIRST FIVE ROWS
# ------------------------------------------------------------

# Display a heading before showing the first five rows
print("\nFIRST FIVE ROWS:")


# Display the first five rows of the combined M4D dataset
display(
    m4d_mouse_dataframe.head()
)

COLUMN NAMES:
['session_id', 'phase', 'label', 'mouse_events', 'duration_seconds', 'total_distance', 'avg_speed']

DATASET SIZE:
Rows: 499
Columns: 7

PHASE COUNTS:
phase
Phase 2    299
Phase 1    200
Name: count, dtype: int64

LABEL COUNTS:
label
Advanced Bot    170
Moderate Bot    170
Human           159
Name: count, dtype: int64

MISSING VALUES:
session_id          0
phase               0
label               0
mouse_events        0
duration_seconds    0
total_distance      0
avg_speed           0
dtype: int64

DUPLICATE SESSION IDs: 50

DATA TYPES:
session_id           object
phase                object
label                object
mouse_events          int64
duration_seconds    float64
total_distance      float64
avg_speed           float64
dtype: object

FIRST FIVE ROWS:

,session_id,phase,label,mouse_events,duration_seconds,total_distance,avg_speed
0,0i5kvpslrq3vb6u8ff2kuejv0v,Phase 1,Advanced Bot,8584,460.995,90825.917680,197.021481
1,1afcff96kgdbmevi5aemi5mkuj,Phase 1,Advanced Bot,7871,422.112,82255.555435,194.866660
2,1aqgqrcuurlmvvbbpirvsh7e53,Phase 1,Human,12182,310.202,125567.991635,404.794268
3,16r8lv9fabgjk06di8usnmu9ni,Phase 1,Advanced Bot,9402,427.428,94552.040289,221.211620
4,071tbv7fsev5d64kb0f9jieor6,Phase 1,Advanced Bot,12413,677.103,127571.108247,188.407241

#STEP 13 - Checking the duplicate sessions

In [ ]:
# ============================================================
# STEP 13 : CHECK DUPLICATE SESSIONS
# ============================================================


# Find all rows that have a repeated session ID
duplicate_sessions = (

    # Select rows from the combined M4D dataset
    m4d_mouse_dataframe[

        # Check the session_id column for duplicate values
        m4d_mouse_dataframe["session_id"].duplicated(

            # Mark all occurrences of a duplicated session ID
            keep=False
        )
    ]
)


# Display the total number of duplicated session rows found
print(
    "Number of duplicated session rows:",
    len(duplicate_sessions)
)


# Check whether any duplicated session rows were found
if len(duplicate_sessions) > 0:


    # Display a heading for the duplicated sessions
    print("\nDuplicated sessions:")


    # Display all rows containing duplicated session IDs
    display(
        duplicate_sessions
    )


# Run this section when no duplicate sessions are found
else:


    # Display a message confirming no duplicate session IDs were found
    print(
        "No duplicate session IDs found"
    )

Number of duplicated session rows: 100

Duplicated sessions:

,session_id,phase,label,mouse_events,duration_seconds,total_distance,avg_speed
2,1aqgqrcuurlmvvbbpirvsh7e53,Phase 1,Human,12182,310.202,125567.991635,404.794268
5,0oa2dua3mli7mrr32c0gd4o0i2,Phase 1,Human,6933,160.409,85250.081718,531.454480
6,0p0kaqfmftrtfg0u12rkshrdi9,Phase 1,Human,6577,210.507,54442.552458,258.625853
7,1r170g6lqfoff21od5nn9f976a,Phase 1,Human,15834,445.151,163707.745609,367.757785
10,26v7bi8e0oc7p58e3s9v8eic9f,Phase 1,Human,15913,494.731,137948.517641,278.835403
...,...,...,...,...,...,...,...
184,ss0e28413uif2hd88q186t7tj8,Phase 1,Human,13517,439.940,134134.613030,304.892970
189,t1eo5hqdtq21m7t0gulu2henl0,Phase 1,Human,8252,232.357,80880.832239,348.088640
192,ufaj0lbcmqa0l022l9jan5n87l,Phase 1,Human,9468,241.772,97367.578050,402.724791
193,v7qok0dv5ekcaoefquadgka6me,Phase 1,Human,10608,299.052,105453.882807,352.627245
198,vopb1c4o3o2dpsov8jinbbou5h,Phase 1,Human,17761,544.627,181632.244250,333.498420

#STEP 14 - Verifying the duplicate sessions

In [ ]:
# ============================================================
# STEP 14 : COMPARE DUPLICATE SESSION IDs
# ============================================================


# Count duplicated session rows by phase

duplicate_phase_counts = (

    # Select the phase column from the duplicated sessions
    duplicate_sessions["phase"]

    # Count how many duplicated rows belong to each phase
    .value_counts()

)


# Display duplicate session rows by phase

print(
    "Duplicate rows by phase:"
)

print(
    duplicate_phase_counts
)


# Count duplicated session rows by class label

duplicate_label_counts = (

    # Select the label column from the duplicated sessions
    duplicate_sessions["label"]

    # Count how many duplicated rows belong to each label
    .value_counts()

)


# Display duplicate session rows by label

print(
    "\nDuplicate rows by label:"
)

print(
    duplicate_label_counts
)


# Count how many times each duplicated session ID appears

duplicate_id_counts = (

    # Select the session_id column from duplicated sessions
    duplicate_sessions["session_id"]

    # Count the occurrences of every repeated session ID
    .value_counts()

)


# Display how many times the duplicated session IDs appear

print(
    "\nNumber of times each duplicate ID appears:"
)

print(
    duplicate_id_counts.value_counts()
)


# Count the number of unique repeated session IDs

unique_duplicate_ids = (

    # Select the session_id column
    duplicate_sessions["session_id"]

    # Count unique duplicated session IDs
    .nunique()

)


# Display the number of unique repeated session IDs

print(
    "\nUnique repeated session IDs:",
    unique_duplicate_ids
)


# Sort duplicated session rows by session ID and phase

duplicate_sessions_sorted = (

    # Use the duplicated session dataset
    duplicate_sessions

    # Sort matching session IDs next to each other
    .sort_values(
        by=[
            "session_id",
            "phase"
        ]
    )

)


# Display the first 20 sorted duplicated session rows

print(
    "\nFirst 20 duplicate session rows:"
)

display(

    # Display only the first 20 rows
    duplicate_sessions_sorted.head(
        20
    )

)

Duplicate rows by phase:
phase
Phase 1    100
Name: count, dtype: int64

Duplicate rows by label:
label
Human    100
Name: count, dtype: int64

Number of times each duplicate ID appears:
count
2    50
Name: count, dtype: int64

Unique repeated session IDs: 50

First 20 duplicate session rows:

,session_id,phase,label,mouse_events,duration_seconds,total_distance,avg_speed
5,0oa2dua3mli7mrr32c0gd4o0i2,Phase 1,Human,6933,160.409,85250.081718,531.454480
102,0oa2dua3mli7mrr32c0gd4o0i2,Phase 1,Human,6933,160.409,85250.081718,531.454480
6,0p0kaqfmftrtfg0u12rkshrdi9,Phase 1,Human,6577,210.507,54442.552458,258.625853
103,0p0kaqfmftrtfg0u12rkshrdi9,Phase 1,Human,6577,210.507,54442.552458,258.625853
2,1aqgqrcuurlmvvbbpirvsh7e53,Phase 1,Human,12182,310.202,125567.991635,404.794268
106,1aqgqrcuurlmvvbbpirvsh7e53,Phase 1,Human,12182,310.202,125567.991635,404.794268
7,1r170g6lqfoff21od5nn9f976a,Phase 1,Human,15834,445.151,163707.745609,367.757785
105,1r170g6lqfoff21od5nn9f976a,Phase 1,Human,15834,445.151,163707.745609,367.757785
10,26v7bi8e0oc7p58e3s9v8eic9f,Phase 1,Human,15913,494.731,137948.517641,278.835403
111,26v7bi8e0oc7p58e3s9v8eic9f,Phase 1,Human,15913,494.731,137948.517641,278.835403
14,49rbuft0lmtfjd3qn70np3lk51,Phase 1,Human,15157,438.815,127411.043897,290.352526
112,49rbuft0lmtfjd3qn70np3lk51,Phase 1,Human,15157,438.815,127411.043897,290.352526
15,4mae49mh8va4g03vjatfn6np9b,Phase 1,Human,10640,254.755,93401.043717,366.630856
119,4mae49mh8va4g03vjatfn6np9b,Phase 1,Human,10640,254.755,93401.043717,366.630856
19,75ufmqjcbcd722b8qt9sdvphdi,Phase 1,Human,10715,377.471,103845.561193,275.108713
113,75ufmqjcbcd722b8qt9sdvphdi,Phase 1,Human,10715,377.471,103845.561193,275.108713
23,7el564n2rvpqj7hl5gn3b8uk8j,Phase 1,Human,11910,284.206,132769.648694,467.159908
117,7el564n2rvpqj7hl5gn3b8uk8j,Phase 1,Human,11910,284.206,132769.648694,467.159908
16,7f2bg9n48opuf4ligvtc1dsopr,Phase 1,Human,11277,332.090,107294.827206,323.089606
118,7f2bg9n48opuf4ligvtc1dsopr,Phase 1,Human,11277,332.090,107294.827206,323.089606

#Step 15 - Check exact duplicate rows

In [ ]:
# ============================================================
# STEP 15 : CHECK EXACT DUPLICATE ROWS
# ============================================================


# Check whether complete rows are exactly duplicated

exact_duplicate_rows = (

    # Check all columns in the M4D dataset
    m4d_mouse_dataframe.duplicated()

    # Count the exact duplicate rows
    .sum()
)


# Display the number of exact duplicate rows

print(
    "Exact duplicate rows:",
    exact_duplicate_rows
)

Exact duplicate rows: 50

#STEP 16 - Remove confirmed duplicate sessions

In [ ]:
# ============================================================
# Step 16 : Remove confirmed duplicate sessions
# ============================================================


# Remove repeated session IDs while keeping the first copy
m4d_mouse_dataframe = m4d_mouse_dataframe.drop_duplicates(

    # Use the session ID to identify repeated sessions
    subset="session_id",

    # Keep the first occurrence of each session
    keep="first"
)


# Reset the row numbers after removing duplicate sessions
m4d_mouse_dataframe = m4d_mouse_dataframe.reset_index(

    # Do not keep the old row numbers as a new column
    drop=True
)


# Display the total number of sessions remaining
print(
    "Sessions after duplicate removal:",
    len(m4d_mouse_dataframe)
)


# Count and display any duplicate session IDs still remaining
print(
    "Duplicate session IDs remaining:",
    m4d_mouse_dataframe["session_id"].duplicated().sum()
)

Sessions after duplicate removal: 449
Duplicate session IDs remaining: 0

#STEP 17 - Final dataset validation

In [ ]:
# ============================================================
# Step 17 : Final dataset validation
# ============================================================


# Display the final number of rows and columns
print(
    "Final dataset size:",
    m4d_mouse_dataframe.shape
)


# Display the final Phase 1 and Phase 2 session counts
print("\nFinal phase counts:")

print(
    m4d_mouse_dataframe["phase"].value_counts()
)


# Display the final class label counts
print("\nFinal label counts:")

print(
    m4d_mouse_dataframe["label"].value_counts()
)


# Count the missing values in each column
print("\nMissing values:")

print(
    m4d_mouse_dataframe.isnull().sum()
)


# Count any duplicate session IDs still remaining
print("\nDuplicate session IDs remaining:")

print(
    m4d_mouse_dataframe["session_id"].duplicated().sum()
)


# Count mouse event values that are zero or negative
print("\nInvalid mouse event counts:")

print(
    (m4d_mouse_dataframe["mouse_events"] <= 0).sum()
)


# Count duration values that are zero or negative
print("\nInvalid duration values:")

print(
    (m4d_mouse_dataframe["duration_seconds"] <= 0).sum()
)


# Count total distance values that are negative
print("\nInvalid total distance values:")

print(
    (m4d_mouse_dataframe["total_distance"] < 0).sum()
)


# Count average speed values that are negative
print("\nInvalid average speed values:")

print(
    (m4d_mouse_dataframe["avg_speed"] < 0).sum()
)


# Display the first five rows for a final visual check
print("\nFirst five rows:")

display(
    m4d_mouse_dataframe.head()
)

Final dataset size: (449, 7)

Final phase counts:
phase
Phase 2    299
Phase 1    150
Name: count, dtype: int64

Final label counts:
label
Advanced Bot    170
Moderate Bot    170
Human           109
Name: count, dtype: int64

Missing values:
session_id          0
phase               0
label               0
mouse_events        0
duration_seconds    0
total_distance      0
avg_speed           0
dtype: int64

Duplicate session IDs remaining:
0

Invalid mouse event counts:
0

Invalid duration values:
0

Invalid total distance values:
0

Invalid average speed values:
0

First five rows:

,session_id,phase,label,mouse_events,duration_seconds,total_distance,avg_speed
0,0i5kvpslrq3vb6u8ff2kuejv0v,Phase 1,Advanced Bot,8584,460.995,90825.917680,197.021481
1,1afcff96kgdbmevi5aemi5mkuj,Phase 1,Advanced Bot,7871,422.112,82255.555435,194.866660
2,1aqgqrcuurlmvvbbpirvsh7e53,Phase 1,Human,12182,310.202,125567.991635,404.794268
3,16r8lv9fabgjk06di8usnmu9ni,Phase 1,Advanced Bot,9402,427.428,94552.040289,221.211620
4,071tbv7fsev5d64kb0f9jieor6,Phase 1,Advanced Bot,12413,677.103,127571.108247,188.407241

#STEP 18 - Save the final M4D mouse CSV

In [ ]:
# ============================================================
# Step 18 : Save the final M4D mouse CSV
# ============================================================


# Create the Google Drive path for the final CSV file
m4d_mouse_csv_path = (
    "/content/drive/MyDrive/DISSERTATION/DATASET/PROCESSED CSV FILES/m4d_mouse.csv"
)


# Save the final M4D mouse DataFrame as a CSV file
m4d_mouse_dataframe.to_csv(

    # Use the selected Google Drive file path
    m4d_mouse_csv_path,

    # Do not save the DataFrame row numbers in the CSV
    index=False
)


# Display a message confirming that the CSV was saved
print(
    "M4D mouse CSV saved successfully"
)


# Display the location of the saved CSV file
print(
    "Saved location:",
    m4d_mouse_csv_path
)


# Display the final number of rows and columns saved
print(
    "Final CSV size:",
    m4d_mouse_dataframe.shape
)

M4D mouse CSV saved successfully
Saved location: /content/drive/MyDrive/DISSERTATION/DATASET/PROCESSED CSV FILES/m4d_mouse.csv
Final CSV size: (449, 7)