<a href="https://colab.research.google.com/github/Jeswin-t/MSc-Dissertation-Web-Bot-Analysis/blob/main/Simple_%2B_Semantic_CSV.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#**Simple + Semantic Data Preparation Pipeline**

Step 1: Import required libraries

Step 2: Connect Google Drive

Step 3: Set Simple and Semantic CSV locations

Step 4: Load both CSV files

Step 5: Check number of rows and columns

Step 6: Check column names

Step 7: Check ID and ROBOT columns

Step 8: Check duplicate session IDs

Step 9: Verify the same sessions exist in both datasets

Step 10: Check for unmatched sessions

Step 11: Verify that the class labels match

Step 12: Check columns shared by both datasets

Step 13: Remove duplicated ROBOT label before combining

Step 14: Combine Simple and Semantic by ID

Step 15: Check the combined dataset

Step 16: Verify all sessions were combined

Step 17: Save the combined Simple + Semantic as a new CSV

#Step 1 - Import required libraries

In [ ]:
# ============================================================
# Step 1: Import required libraries
# ============================================================


# Import the Google Drive
from google.colab import drive

# Import Pandas for loading, checking and combining CSV datasets
import pandas as pd


# Import OS for working with file paths and folders
import os

#Step 2 - Connect Google Drive

In [ ]:
# ============================================================
# Step 2: Connect Google Drive
# ============================================================


# Connect Google Drive to the Colab notebook
drive.mount(
    "/content/drive"
)


# Confirm that the connection step is complete
print(
    "Google Drive connected"
)

Mounted at /content/drive
Google Drive connected

#Step 3 - Set the Simple and Semantic CSV locations

In [ ]:
# ============================================================
# Step 3: Set the Simple and Semantic CSV locations
# ============================================================


# Set the location of the Simple Features CSV
simple_csv_path = (
    "/content/drive/MyDrive/DISSERTATION/DATASET/RAW DATASET/Web robot detection - Server logs/simple_features.csv"
)


# Set the location of the Semantic Features CSV
semantic_csv_path = (
    "/content/drive/MyDrive/DISSERTATION/DATASET/RAW DATASET/Web robot detection - Server logs/semantic_features.csv"
)


# Check whether the Simple Features CSV exists
print(
    "Simple CSV found:",
    os.path.exists(simple_csv_path)
)


# Check whether the Semantic Features CSV exists
print(
    "Semantic CSV found:",
    os.path.exists(semantic_csv_path)
)

Simple CSV found: True
Semantic CSV found: True

#Step 4 - Load both CSV files

In [ ]:
# ============================================================
# Step 4: Load both CSV files
# ============================================================


# Load the Simple Features CSV into a Pandas DataFrame
simple_dataframe = pd.read_csv(
    simple_csv_path
)


# Load the Semantic Features CSV into a Pandas DataFrame
semantic_dataframe = pd.read_csv(
    semantic_csv_path
)


# Confirm that both files were loaded
print(
    "Simple and Semantic CSV files loaded successfully"
)

Simple and Semantic CSV files loaded successfully

#Step 5 - Check number of rows and columns

In [ ]:
# ============================================================
# Step 5: Check number of rows and columns
# ============================================================


# Display the number of rows and columns in the Simple Features dataset
print(
    "Simple Features size:",
    simple_dataframe.shape
)


# Display the number of rows and columns in the Semantic Features dataset
print(
    "Semantic Features size:",
    semantic_dataframe.shape
)

Simple Features size: (67352, 32)
Semantic Features size: (67352, 7)

#Step 6 - Inspect column names

In [ ]:
# ============================================================
# Step 6: Inspect column names
# ============================================================


# Display all column names in the Simple Features dataset
print(
    "Simple Features columns:"
)

print(
    simple_dataframe.columns.tolist()
)


# Display all column names in the Semantic Features dataset
print(
    "\nSemantic Features columns:"
)

print(
    semantic_dataframe.columns.tolist()
)

Simple Features columns:
['ID', 'NUMBER_OF_REQUESTS', 'TOTAL_DURATION', 'AVERAGE_TIME', 'STANDARD_DEVIATION', 'REPEATED_REQUESTS', 'HTTP_RESPONSE_2XX', 'HTTP_RESPONSE_3XX', 'HTTP_RESPONSE_4XX', 'HTTP_RESPONSE_5XX', 'GET_METHOD', 'POST_METHOD', 'HEAD_METHOD', 'OTHER_METHOD', 'NIGHT', 'UNASSIGNED', 'IMAGES', 'TOTAL_HTML', 'HTML_TO_IMAGE', 'HTML_TO_CSS', 'HTML_TO_JS', 'WIDTH', 'DEPTH', 'STD_DEPTH', 'CONSECUTIVE', 'DATA', 'PPI', 'SF_REFERRER', 'SF_FILETYPE', 'MAX_BARRAGE', 'PENALTY', 'ROBOT']

Semantic Features columns:
['ID', 'TOTAL_TOPICS', 'UNIQUE_TOPICS', 'PAGE_SIMILARITY', 'PAGE_VARIANCE', 'BOOLEAN_PAGE_VARIANCE', 'ROBOT']

#Step 7 - Check the ID and label columns

In [ ]:
# ============================================================
# Step 7: Check the ID and label columns
# ============================================================


# Check whether ID exists in the Simple Features dataset
print(
    "ID in Simple:",
    "ID" in simple_dataframe.columns
)


# Check whether ID exists in the Semantic Features dataset
print(
    "ID in Semantic:",
    "ID" in semantic_dataframe.columns
)


# Check whether ROBOT exists in the Simple Features dataset
print(
    "ROBOT in Simple:",
    "ROBOT" in simple_dataframe.columns
)


# Check whether ROBOT exists in the Semantic Features dataset
print(
    "ROBOT in Semantic:",
    "ROBOT" in semantic_dataframe.columns
)

ID in Simple: True
ID in Semantic: True
ROBOT in Simple: True
ROBOT in Semantic: True

#Step 8 - Check duplicate session IDs

In [ ]:
# ============================================================
# Step 8: Check duplicate session IDs
# ============================================================


# Select the ID column from the Simple Features dataset
simple_duplicate_ids = (

    simple_dataframe["ID"]

    # Mark IDs that appear more than once
    .duplicated()

    # Count the total number of duplicated IDs
    .sum()
)


# Select the ID column from the Semantic Features dataset
semantic_duplicate_ids = (

    semantic_dataframe["ID"]

    # Mark IDs that appear more than once
    .duplicated()

    # Count the total number of duplicated IDs
    .sum()
)


# Display the number of duplicate IDs in the Simple Features dataset
print(
    "Duplicate IDs in Simple:",
    simple_duplicate_ids
)


# Display the number of duplicate IDs in the Semantic Features dataset
print(
    "Duplicate IDs in Semantic:",
    semantic_duplicate_ids
)

Duplicate IDs in Simple: 0
Duplicate IDs in Semantic: 0

#Step 9 - Verify whether both files contain the same session IDs

In [ ]:
# ============================================================
# Step 9: Verify the same sessions exist in both files
# ============================================================


# Convert the Simple session IDs into a set
simple_ids = set(
    simple_dataframe["ID"]
)


# Convert the Semantic session IDs into a set
semantic_ids = set(
    semantic_dataframe["ID"]
)


# Check whether both datasets contain exactly the same IDs
same_session_ids = (
    simple_ids == semantic_ids
)


# Display the result
print(
    "Both files contain the same session IDs:",
    same_session_ids
)

Both files contain the same session IDs: True

#Step 10 - Check for unmatched sessions

In [ ]:
# ============================================================
# Step 10: Check for unmatched sessions
# ============================================================


# Find session IDs that exist in Simple but not in Semantic
simple_only_ids = (

    # Subtract the Semantic ID set from the Simple ID set
    simple_ids - semantic_ids
)


# Find session IDs that exist in Semantic but not in Simple
semantic_only_ids = (

    # Subtract the Simple ID set from the Semantic ID set
    semantic_ids - simple_ids
)


# Display the number of sessions found only in Simple
print(
    "Sessions only in Simple:",

    # Count the number of unmatched Simple session IDs
    len(simple_only_ids)
)


# Display the number of sessions found only in Semantic
print(
    "Sessions only in Semantic:",

    # Count the number of unmatched Semantic session IDs
    len(semantic_only_ids)
)

Sessions only in Simple: 0
Sessions only in Semantic: 0

#Step 11 - Verify that the Human or Bot labels match

In [ ]:
# ============================================================
# Step 11: Verify that the class labels match
# ============================================================


# Select only the ID and ROBOT columns from the Simple dataset
simple_labels = simple_dataframe[

    # Keep the session ID and class label columns
    ["ID", "ROBOT"]

# Create a separate copy of the selected columns
].copy()


# Select only the ID and ROBOT columns from the Semantic dataset
semantic_labels = semantic_dataframe[

    # Keep the session ID and class label columns
    ["ID", "ROBOT"]

# Create a separate copy of the selected columns
].copy()


# Join the Simple and Semantic label tables using the session ID
label_check = pd.merge(

    # Use the Simple ID and label table
    simple_labels,

    # Use the Semantic ID and label table
    semantic_labels,

    # Match the rows using the ID column
    on="ID",

    # Keep IDs that exist in both tables
    how="inner",

    # Rename the two ROBOT columns so they can be identified separately
    suffixes=(
        "_simple",
        "_semantic"
    )
)


# Compare the Simple and Semantic labels for every matched session
label_mismatches = (

    # Select the ROBOT label from the Simple dataset
    label_check["ROBOT_simple"]

    # Check whether it is different from the Semantic label
    !=

    # Select the ROBOT label from the Semantic dataset
    label_check["ROBOT_semantic"]

# Count the total number of label mismatches
).sum()


# Display the number of sessions with different labels
print(

    # Display a description of the result
    "Label mismatches:",

    # Display the total number of mismatched labels
    label_mismatches
)

Label mismatches: 0

#Step 12 - Check columns shared by both datasets

In [ ]:
# ============================================================
# Step 12: Check columns shared by both datasets
# ============================================================


# Get all column names from the Simple Features dataset
common_columns = set(
    simple_dataframe.columns

# Find the column names that also exist in the Semantic Features dataset
).intersection(
    semantic_dataframe.columns
)


# Display a heading for the shared columns
print(
    "Columns present in both files:"
)


# Sort and display the shared column names
print(
    sorted(common_columns)
)

Columns present in both files:
['ID', 'ROBOT']

#Step 13 - Remove duplicated ROBOT label before combining

In [ ]:
# ==================================================================================
# Step 13: Keep ID for matching and remove duplicate ROBOT label before combining
# ==================================================================================


# Remove ROBOT from Semantic because the same label already exists in Simple
semantic_features_only = semantic_dataframe.drop(

    # Remove only the repeated ROBOT column
    columns=[
        "ROBOT"
    ]
)


# Display the Semantic columns that will be used for combining
print(
    "Semantic columns ready for combining:"
)


# Show the remaining Semantic column names
print(
    semantic_features_only.columns.tolist()
)

Semantic columns ready for combining:
['ID', 'TOTAL_TOPICS', 'UNIQUE_TOPICS', 'PAGE_SIMILARITY', 'PAGE_VARIANCE', 'BOOLEAN_PAGE_VARIANCE']

#Step 14 - Combine Simple and Semantic datasets

In [ ]:
# ============================================================
# Step 14: Combine Simple and Semantic by ID
# ============================================================


# Combine the Simple and Semantic datasets
simple_semantic_dataframe = pd.merge(

    # Use Simple as the main dataset
    simple_dataframe,

    # Add the Semantic features without the repeated ROBOT column
    semantic_features_only,

    # Match sessions using their ID
    on="ID",

    # Keep sessions that are present in both datasets
    how="inner",

    # Make sure each ID matches only one ID
    validate="one_to_one"
)


# Display the number of rows and columns after combining
print(
    "Combined dataset size:",
    simple_semantic_dataframe.shape
)


# Display the first Ten rows of the combined dataset
display(
    simple_semantic_dataframe.head(10)
)

Combined dataset size: (67352, 37)

,ID,NUMBER_OF_REQUESTS,TOTAL_DURATION,AVERAGE_TIME,STANDARD_DEVIATION,REPEATED_REQUESTS,HTTP_RESPONSE_2XX,HTTP_RESPONSE_3XX,HTTP_RESPONSE_4XX,HTTP_RESPONSE_5XX,...,SF_REFERRER,SF_FILETYPE,MAX_BARRAGE,PENALTY,ROBOT,TOTAL_TOPICS,UNIQUE_TOPICS,PAGE_SIMILARITY,PAGE_VARIANCE,BOOLEAN_PAGE_VARIANCE
0,obSnwGoBCue8G08E_WCX,79,592,7.589744,1.800540,0.000000,0.873418,0.126582,0.000000,0.000000,...,0.000000,0.205128,1,0,1,242,500,2.066116,92.259556,0.165414
1,nLSnwGoBCue8G08E_WCX,350,103621,296.908300,260.332670,0.000000,0.997143,0.000000,0.002857,0.000000,...,0.547278,0.461318,4,0,1,966,500,0.517598,55.603497,0.168825
2,ErSowGoBCue8G08ECmHa,15,368,26.285715,87.329780,0.000000,1.000000,0.000000,0.000000,0.000000,...,0.642857,1.000000,2,0,0,51,500,9.803922,29.972318,0.138156
3,E7SowGoBCue8G08ECmHa,28,11,0.407407,1.097447,0.000000,1.000000,0.000000,0.000000,0.000000,...,0.037037,0.148148,5,0,0,77,500,6.493506,63.287982,0.136179
4,FbSowGoBCue8G08ECmHa,9342,80946,8.665668,17.566462,0.000107,0.996896,0.002569,0.000214,0.000321,...,0.000000,0.023552,1,0,1,1922,500,0.260146,50.443596,0.179579
5,FrSowGoBCue8G08ECmHa,11,96,9.600000,26.161804,0.000000,1.000000,0.000000,0.000000,0.000000,...,0.200000,0.400000,6,0,0,7,5,0.714286,1.111111,0.103809
6,F7SowGoBCue8G08ECmHa,98,36,0.371134,1.795295,0.000000,1.000000,0.000000,0.000000,0.000000,...,0.113402,0.309278,30,0,0,174,500,2.873563,42.554017,0.165150
7,GbSowGoBCue8G08ECmHa,12,262,23.818182,20.475342,0.083333,1.000000,0.000000,0.000000,0.000000,...,1.000000,0.545455,1,4,0,50,500,10.000000,121.520833,0.087901
8,HbSowGoBCue8G08ECmHa,186,477,2.578378,7.437347,0.032258,1.000000,0.000000,0.000000,0.000000,...,0.172973,0.329730,32,4,0,489,500,1.022495,51.409974,0.160723
9,HrSowGoBCue8G08ECmHa,11,20,2.000000,4.427189,0.090909,1.000000,0.000000,0.000000,0.000000,...,0.200000,0.600000,3,0,0,20,500,25.000000,0.000000,0.000000

#Step 15 - Check the combined dataset

In [ ]:
# ============================================================
# Step 15: Check the combined dataset
# ============================================================


# Display the number of rows and columns in the combined dataset
print(

    # Display a description for the result
    "Combined dataset size:",

    # Get the number of rows and columns
    simple_semantic_dataframe.shape
)


# Display the number of unique session IDs
print(

    # Display a description for the result
    "Unique session IDs:",

    # Select the ID column and count unique IDs
    simple_semantic_dataframe["ID"].nunique()
)


# Display the number of duplicate session IDs
print(

    # Display a description for the result
    "Duplicate session IDs:",

    # Select the ID column, find duplicates and count them
    simple_semantic_dataframe["ID"].duplicated().sum()
)


# Display a heading for the Human and Bot class counts
print(
    "\nClass label counts:"
)


# Select the ROBOT column and count each class label
print(
    simple_semantic_dataframe["ROBOT"].value_counts()
)


# Display a heading for the first five rows
print(
    "\nFirst five rows:"
)


# Select and display the first five rows of the combined dataset
display(
    simple_semantic_dataframe.head()
)

Combined dataset size: (67352, 37)
Unique session IDs: 67352
Duplicate session IDs: 0

Class label counts:
ROBOT
0    53858
1    13494
Name: count, dtype: int64

First five rows:

,ID,NUMBER_OF_REQUESTS,TOTAL_DURATION,AVERAGE_TIME,STANDARD_DEVIATION,REPEATED_REQUESTS,HTTP_RESPONSE_2XX,HTTP_RESPONSE_3XX,HTTP_RESPONSE_4XX,HTTP_RESPONSE_5XX,...,SF_REFERRER,SF_FILETYPE,MAX_BARRAGE,PENALTY,ROBOT,TOTAL_TOPICS,UNIQUE_TOPICS,PAGE_SIMILARITY,PAGE_VARIANCE,BOOLEAN_PAGE_VARIANCE
0,obSnwGoBCue8G08E_WCX,79,592,7.589744,1.800540,0.000000,0.873418,0.126582,0.000000,0.000000,...,0.000000,0.205128,1,0,1,242,500,2.066116,92.259556,0.165414
1,nLSnwGoBCue8G08E_WCX,350,103621,296.908300,260.332670,0.000000,0.997143,0.000000,0.002857,0.000000,...,0.547278,0.461318,4,0,1,966,500,0.517598,55.603497,0.168825
2,ErSowGoBCue8G08ECmHa,15,368,26.285715,87.329780,0.000000,1.000000,0.000000,0.000000,0.000000,...,0.642857,1.000000,2,0,0,51,500,9.803922,29.972318,0.138156
3,E7SowGoBCue8G08ECmHa,28,11,0.407407,1.097447,0.000000,1.000000,0.000000,0.000000,0.000000,...,0.037037,0.148148,5,0,0,77,500,6.493506,63.287982,0.136179
4,FbSowGoBCue8G08ECmHa,9342,80946,8.665668,17.566462,0.000107,0.996896,0.002569,0.000214,0.000321,...,0.000000,0.023552,1,0,1,1922,500,0.260146,50.443596,0.179579

#Step 16 - Verify all sessions were combined

In [ ]:
# ============================================================
# Step 16: Verify all sessions were combined
# ============================================================


# Create a variable to store the number of Simple sessions
simple_session_count = len(

    # Count all rows in the Simple dataset
    simple_dataframe
)


# Create a variable to store the number of combined sessions
combined_session_count = len(

    # Count all rows in the combined dataset
    simple_semantic_dataframe
)


# Create a variable to store the number of sessions lost
sessions_lost = (

    # Take the original number of Simple sessions
    simple_session_count

    # Subtract the number of combined sessions
    -
    combined_session_count
)


# Display the original Simple session count
print(

    # Display the result name
    "Original Simple sessions:",

    # Display the number of Simple sessions
    simple_session_count
)


# Display the combined session count
print(

    # Display the result name
    "Combined sessions:",

    # Display the number of combined sessions
    combined_session_count
)


# Display how many sessions were lost
print(

    # Display the result name
    "Sessions lost during combining:",

    # Display the calculated number of lost sessions
    sessions_lost
)

Original Simple sessions: 67352
Combined sessions: 67352
Sessions lost during combining: 0

#Step 17 - Save the combined Simple + Semantic as a new CSV

In [ ]:
# ============================================================
# Step 17: Save the combined dataset
# ============================================================


# Create the file path where the combined CSV will be saved
combined_csv_path = (

    # Set the Google Drive location and CSV file name
    "/content/drive/MyDrive/DISSERTATION/DATASET/PROCESSED CSV FILES/simple_semantic_combined.csv"
)


# Save the combined DataFrame as a CSV file
simple_semantic_dataframe.to_csv(

    # Save the CSV in the selected location
    combined_csv_path,

    # Do not include Pandas row numbers in the CSV
    index=False
)


# Display a message to confirm that the file was saved
print(
    "Combined CSV saved successfully"
)


# Display the location of the saved CSV
print(

    # Display the result name
    "Saved location:",

    # Display the file path
    combined_csv_path
)


# Display the number of rows and columns in the saved dataset
print(

    # Display the result name
    "Final CSV size:",

    # Display the rows and columns
    simple_semantic_dataframe.shape
)

Combined CSV saved successfully
Saved location: /content/drive/MyDrive/DISSERTATION/DATASET/PROCESSED CSV FILES/simple_semantic_combined.csv
Final CSV size: (67352, 37)